# Generated by Django 4.2.7 on 2025-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='JobLift – AI-Powered ATS Resume Optimizer & Job Matcher', max_length=200)),
                ('subtitle', models.TextField(default='Boost your career with JobLift. Optimize your CV for Applicant Tracking Systems (ATS), get a higher resume score, and discover tailored job opportunities.')),
                ('background_video', models.URLField(blank=True, help_text='YouTube or video URL', null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_text', models.CharField(default='Get Started', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.AlterModelOptions(
            name='interviewresource',
            options={},
        ),
        migrations.AlterField(
            model_name='interviewresource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('practice', 'Practice'), ('tips', 'Tips')], max_length=20),
        ),
    ]
