# Generated by Django 4.2.7 on 2025-10-08 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='created_cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('professional', 'Professional'), ('minimal', 'Minimal')], max_length=20)),
                ('description', models.TextField()),
                ('html_template', models.TextField()),
                ('css_styles', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cv_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cvupload',
            name='analysis_report',
        ),
        migrations.AlterField(
            model_name='atskeyword',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='job_role',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
        migrations.AddField(
            model_name='createdcv',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_optimizer.cvtemplate'),
        ),
        migrations.AddField(
            model_name='createdcv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
