# Generated by Django 4.2.7 on 2025-10-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_optimizer', '0002_createdcv_cvtemplate_remove_cvupload_analysis_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='gemini_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvupload',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvupload',
            name='job_match_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cvupload',
            name='keyword_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvupload',
            name='missing_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvupload',
            name='optimized_content',
            field=models.TextField(blank=True),
        ),
    ]
