# Generated by Django 4.2.7 on 2025-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobalert',
            name='job_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userjobalert',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
